Fix role_arns local variable (#105)
This local variable was renamed in 99cf52e but this was missed and is
causing Terraform to fail.

```
Error: module.elasticsearch.var.iam_role_arns: local.arns: no local value of this name has been declared
```